name: Test
on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: "11 21 * * *"
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make test
